services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: [ "sh", "-c", ".docker/bootstrap.sh" ]

  web:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: lumos
      POSTGRES_USER: lumos
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
      - .docker/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
      - 8081:8080
    volumes:
      - ./openapi.yml:/openapi.yml:ro
    environment:
      SWAGGER_JSON: /openapi.yml
    depends_on:
      - app

volumes:
  dbdata: null
  redisdata: null
